#!/bin/bash
set -u

export ME_ERROR_GENERAL=1
export ME_ERROR_SETUP_ALL=200
export ME_ERROR_TO_NEXT=210
export ME_ERROR_TO_RETRY=211
export ME_ERROR_WITH_REBOOT_TO_NEXT=212
export ME_ERROR_WITH_REBOOT_TO_RETRY=213

export ME_CONTROL_ERROR=220
export ME_CONTROL_REPEAT_ERROR=221
export ME_CONTROL_FATAL_ERROR=222
